# Generated by Django 3.2.4 on 2021-06-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='cms_img',
            field=models.ImageField(default=2, upload_to='sliderimg/'),
            preserve_default=False,
        ),
    ]
