# Generated by Django 3.2.4 on 2021-06-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmsslider_cms_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_img',
            field=models.ImageField(blank=True, upload_to='sliderimg/'),
        ),
    ]
