# Generated by Django 3.2.4 on 2021-06-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_order_order_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_surname',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Surname'),
        ),
    ]
